# Generated by Django 3.0.2 on 2020-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=100)),
                ('post_image_one', models.ImageField(blank=True, upload_to='img')),
                ('updated_one', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
