# Generated by Django 3.0.2 on 2020-09-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_dailyblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyBlog',
        ),
    ]
